apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdb-controller
  labels:
    application: pdb-controller
    version: latest
spec:
  selector:
    matchLabels:
      application: pdb-controller
  template:
    metadata:
      labels:
        application: pdb-controller
        version: latest
    spec:
      containers:
      - name: pdb-controller
        image: harshals/pdb-controller:v0.0.9
        args:
        - "--debug"
        - "--namespace-selector"
        - "use-pdb=true"
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 25Mi
      serviceAccount: pdb-controller